"""Documentation generator: renders `docs/checks.md` from the live check
registry (`checks.registry.CHECKS`) so the published catalog can never drift
from what the package actually runs — the same "one source of truth"
discipline as `checks.registry.ruleset_digest()`.

`render_checks()` is deterministic (sorted by category, then check id) and
pure — it reads only already-imported module state, no I/O. `render_weights_table()`
renders the public scoring constants (`scoring.CATEGORY_WEIGHTS`,
`scoring.MIN_COVERAGE`, `scoring.GRADES`) for `docs/methodology.md`, which embeds
its output verbatim; both a test and the Cloud-side sync
tripwire pin the committed docs to these two functions' current output.

Run `python -m scovant_core.docs` after any check/scoring change to
regenerate `docs/checks.md`. `render_example()` renders the committed
`docs/example-report.md` from the `commerce-good` golden fixture (never a
live scan, so the published example can't drift from the engine or leak a
real third party's score) — regenerate it with
`python -m scovant_core.docs --example` after any change to the renderer,
the fixture, or the scoring model. `write_plugin_references()` copies the
same generated checks/AgentReady catalog plus the committed methodology and
report-schema docs into `claude-plugin/skills/references/` so the Claude
Code plugin ships an offline reference — regenerate with
`python -m scovant_core.docs --plugin` after any change to those four
sources.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

from scovant_core import checks as _checks  # noqa: F401 — importing populates registry.CHECKS
from scovant_core.checks.registry import CHECKS
from scovant_core.models import CATEGORY_TITLES, Category
from scovant_core.scoring import CATEGORY_WEIGHTS, GRADES, MIN_COVERAGE, SCORED_CATEGORIES

__all__ = [
    "HEADER",
    "render_checks",
    "render_weights_table",
    "render_example",
    "render_agentready",
    "write_plugin_references",
    "main",
]

HEADER = "<!-- generated by python -m scovant_core.docs — do not edit -->"

# `docs/checks.md` lives at the package root's `docs/` directory:
# src/scovant_core/docs.py -> parents[0]=scovant_core parents[1]=src parents[2]=<pkg root>
_DOCS_PATH = Path(__file__).resolve().parents[2] / "docs" / "checks.md"
_STANDARDS_PATH = _DOCS_PATH.parent / "standards" / "agentready.md"


def _profiles_cell(profiles: frozenset[str] | None) -> str:
    return "all" if profiles is None else ", ".join(sorted(profiles))


def _first_sentence(text: str) -> str:
    """The `Status:` line quotes WHY a check exists in one sentence; the full
    prose stays in the `Why it matters` line right above it, so this never
    needs to be smart — just not to truncate mid-sentence."""
    return re.split(r"(?<=[.!?])\s+", text.strip(), maxsplit=1)[0]


def _checks_by_category() -> dict[Category, list]:
    grouped: dict[Category, list] = {cat: [] for cat in Category}
    for c in CHECKS:
        grouped[c.category].append(c)
    for cat_checks in grouped.values():
        cat_checks.sort(key=lambda c: c.id)
    return grouped


def render_checks() -> str:
    grouped = _checks_by_category()
    lines: list[str] = [
        HEADER,
        "",
        "# Scovant Core Checks",
        "",
        (
            "Every check the package can run, grouped by category. Regenerated from "
            "`checks/registry.py` by `python -m scovant_core.docs` — do not hand-edit this file."
        ),
        "",
    ]
    for cat in Category:
        cat_checks = grouped[cat]
        if not cat_checks:
            continue
        lines.append(f"## {CATEGORY_TITLES[cat]}")
        lines.append("")
        if cat == Category.SECURITY:
            # Every check row carries a `Weight` column, and a reader who
            # has just read five scored sections will read that column the
            # same way here. It is inert for this category.
            lines.append("Weight is informational — security checks are never scored.")
            lines.append("")
            # SECURITY checks carry two extra dimensions readiness checks
            # don't: which family (attack surface) they belong to, and how
            # the evidence was obtained (`verification_mode`) — both are
            # load-bearing for a reader deciding how much to trust a
            # finding, so they get their own columns here rather than
            # being buried in prose. Readiness sections keep the original
            # table shape so their `checks.md` diff stays minimal.
            lines.append("| ID | Title | Family | Verification | Weight | Profiles | Severity on fail | Experimental |")
            lines.append("|---|---|---|---|---|---|---|---|")
            for c in cat_checks:
                lines.append(
                    f"| {c.id} | {c.title} | {c.family_id} | {c.verification_mode} | {c.weight} "
                    f"| {_profiles_cell(c.profiles)} | {c.severity_on_fail.value} "
                    f"| {'yes' if c.experimental else 'no'} |"
                )
        else:
            lines.append("| ID | Title | Weight | Profiles | Severity on fail | Experimental |")
            lines.append("|---|---|---|---|---|---|")
            for c in cat_checks:
                lines.append(
                    f"| {c.id} | {c.title} | {c.weight} | {_profiles_cell(c.profiles)} "
                    f"| {c.severity_on_fail.value} | {'yes' if c.experimental else 'no'} |"
                )
        lines.append("")
        for c in cat_checks:
            lines.append(f"### {c.id} — {c.title}")
            lines.append("")
            lines.append(f"**Why it matters:** {c.why_it_matters}")
            lines.append("")
            if cat == Category.SECURITY:
                lines.append(
                    f"**Family:** {c.family_id} · **Verification:** {c.verification_mode} · "
                    f"**Domain:** {c.security_domain} · **Fix owner:** {c.fix_owner}"
                )
                lines.append("")
            if c.experimental:
                # An experimental check must publish its own exit criteria, not
                # just its experimental flag (`promotion_criteria` is required on
                # every experimental check by `tests/test_registry.py`).
                lines.append(
                    f"**Status:** experimental · scored: no · reason: {_first_sentence(c.why_it_matters)}"
                    f" · promotion: {c.promotion_criteria}"
                )
                lines.append("")
            lines.append(f"**Limitations:** {c.limitations}")
            lines.append("")
            if c.standards:
                lines.append("**Standards:** " + ", ".join(c.standards))
                lines.append("")
            if c.cloud_extension:
                lines.append(f"**Cloud extension:** {c.cloud_extension}")
                lines.append("")
            if c.references:
                lines.append("**References:**")
                lines.append("")
                for ref in c.references:
                    lines.append(f"- <{ref}>")
                lines.append("")
    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines) + "\n"


def _grade_ranges() -> list[tuple[int, int, str]]:
    ordered = sorted(GRADES, key=lambda pair: pair[0], reverse=True)
    ranges: list[tuple[int, int, str]] = []
    upper = 100
    for floor, grade in ordered:
        ranges.append((floor, upper, grade))
        upper = floor - 1
    return ranges


def render_weights_table() -> str:
    # SCORED_CATEGORIES, not Category — SECURITY carries no weight (see
    # scoring.SCORED_CATEGORIES) and has no entry in CATEGORY_WEIGHTS.
    lines: list[str] = ["| Category | Weight |", "|---|---:|"]
    for cat in SCORED_CATEGORIES:
        lines.append(f"| {CATEGORY_TITLES[cat]} | {CATEGORY_WEIGHTS[cat.value]} |")
    lines.append(f"| **Total** | **{sum(CATEGORY_WEIGHTS.values())}** |")
    lines.append("")
    lines.append(
        f"Minimum evidence coverage: {round(MIN_COVERAGE * 100)}%. Below this coverage, "
        "no score is emitted (`INSUFFICIENT_EVIDENCE`) instead of scoring on whatever few "
        "checks happened to evaluate."
    )
    lines.append("")
    lines.append("| Score | Grade |")
    lines.append("|---|---|")
    for floor, upper, grade in _grade_ranges():
        lines.append(f"| {floor}–{upper} | {grade} |")
    return "\n".join(lines)


def render_example() -> str:
    """The published example report, rendered from the `commerce-good` golden
    fixture — never from a live scan, so it cannot drift from the engine and
    never publishes a real third party's score."""
    import json

    from scovant_core.models import Report
    from scovant_core.report.markdown import render_markdown

    golden = Path(__file__).resolve().parents[2] / "fixtures" / "sites" / "expected" / "commerce-good.json"
    report = Report.model_validate(json.loads(golden.read_text(encoding="utf-8")))
    return (
        "# Example report\n\n"
        "Generated from the `commerce-good` fixture by "
        "`python -m scovant_core.docs --example`. Do not edit by hand.\n\n"
        + render_markdown(report, utm_medium="docs").rstrip("\n") + "\n"
    )


_EXAMPLE_PATH = Path(__file__).resolve().parents[2] / "docs" / "example-report.md"


def render_agentready() -> str:
    """The AgentReady v1.0 mapping doc (`docs/standards/agentready.md`), rendered
    from `standards.agentready.REQUIREMENTS`/`MAPPING` — pure and deterministic,
    no I/O beyond the already-imported module state. Regenerate with
    `python -m scovant_core.docs --standards` after any mapping change."""
    from scovant_core.standards.agentready import (
        AGENTREADY_URL,
        AGENTREADY_VERSION,
        MAPPING,
        REQUIREMENTS,
        mapping_summary,
    )
    s = mapping_summary()
    by_id = {m.requirement_id: m for m in MAPPING}
    lines = [
        HEADER, "", f"# Scovant Core ↔ AgentReady v{AGENTREADY_VERSION}", "",
        (f"AgentReady (<{AGENTREADY_URL}>, v{AGENTREADY_VERSION}, MIT) defines requirements, not weights: "
         "scoring belongs to scanners, and Scovant Core reproduces no third-party score. This page "
         "lists which AgentReady requirements Scovant Core checks measure, and how faithfully. It is "
         "regenerated by `python -m scovant_core.docs --standards` — do not hand-edit."), "",
        (f"Summary: {s['requirements']} requirements; {s['with_checks']} measured by Core checks "
         f"({s['exact']} exact, {s['partial']} partial, {s['superset']} superset); "
         f"{s['agentready_only']} not measured by Core; {s['not_applicable']} not applicable to a passive scanner."), "",
        "## Relationship legend", "",
        "| Relationship | Meaning |", "|---|---|",
        "| EXACT | The check's evidence is the requirement's evidence. |",
        "| PARTIAL | The check measures a narrower slice; the gap is in the notes. |",
        "| SCOVANT_SUPERSET | Core checks strictly more than the requirement asks. |",
        "| AGENTREADY_ONLY | Core does not measure this requirement. |",
        "| NOT_APPLICABLE | Not a website signal a passive scanner can read. |", "",
        "## Mapping", "",
        "| AgentReady | Tier | Title | Core checks | Relationship | Notes |", "|---|---|---|---|---|---|",
    ]
    for r in REQUIREMENTS:
        m = by_id[r.id]
        checks = ", ".join(m.core_checks) if m.core_checks else "—"
        lines.append(f"| {r.id} | {r.tier} | {r.title} | {checks} | {m.relationship} | {m.notes} |")
    return "\n".join(lines) + "\n"


_PLUGIN_REFS = Path(__file__).resolve().parents[2] / "claude-plugin" / "skills" / "references"


def write_plugin_references() -> list[Path]:
    """The Claude Code plugin ships offline copies of the check catalog,
    methodology, AgentReady standard and report schema so `/scovant:explain`
    works without the MCP server. They are GENERATED — pinned byte-equal to
    their sources by tests/test_claude_plugin.py. Writes to `_PLUGIN_REFS`
    (module-level, monkeypatched by tests — there is no caller that needs a
    different target at runtime)."""
    root = _PLUGIN_REFS
    root.mkdir(parents=True, exist_ok=True)
    docs = _DOCS_PATH.parent
    out = {
        "checks.md": render_checks().encode("utf-8"),
        "agentready.md": render_agentready().encode("utf-8"),
        "methodology.md": (docs / "methodology.md").read_bytes(),
        "report.schema.json": (docs / "report.schema.json").read_bytes(),
    }
    written = []
    for name, data in out.items():
        (root / name).write_bytes(data)
        written.append(root / name)
    return written


def main(argv: list[str] | None = None) -> int:
    """`python -m scovant_core.docs [--example|--standards|--plugin]` —
    rewrites the committed `docs/checks.md`, `docs/example-report.md` with
    `--example`, `docs/standards/agentready.md` with `--standards`, or the
    Claude Code plugin's offline references with `--plugin`."""
    args = list(sys.argv[1:] if argv is None else argv)
    unknown = [a for a in args if a not in ("--example", "--standards", "--plugin")]
    if unknown:
        print(
            f"usage: python -m scovant_core.docs [--example|--standards|--plugin] "
            f"(unknown argument: {unknown[0]})",
            file=sys.stderr,
        )
        return 2
    if not _DOCS_PATH.parent.is_dir():
        print("python -m scovant_core.docs writes the repository's docs/ directory, which is "
              "not present here (installed package?). Run it from a checkout.", file=sys.stderr)
        return 2
    if "--example" in args:
        _EXAMPLE_PATH.write_text(render_example(), encoding="utf-8")
    elif "--standards" in args:
        _STANDARDS_PATH.parent.mkdir(parents=True, exist_ok=True)
        _STANDARDS_PATH.write_text(render_agentready(), encoding="utf-8")
    elif "--plugin" in args:
        write_plugin_references()
    else:
        _DOCS_PATH.write_text(render_checks(), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
