"""Documentation generator: renders `docs/checks.md` from the live check
registry (`checks.registry.CHECKS`) so the published catalog can never drift
from what the package actually runs — the same "one source of truth"
discipline as `checks.registry.ruleset_digest()`.

`render_checks()` is deterministic (sorted by category, then check id) and
pure — it reads only already-imported module state, no I/O. `render_weights_table()`
renders the public scoring constants (`scoring.CATEGORY_WEIGHTS`,
`scoring.MIN_COVERAGE`, `scoring.GRADES`) for `docs/methodology.md`, which embeds
its output verbatim; `tests/test_docs.py` and the Cloud-side sync tripwire
(`test_scovant_core_sync.py`) both pin the committed docs to these two
functions' current output.

Run `python -m scovant_core.docs` after any check/scoring change to
regenerate `docs/checks.md`. `render_example()` renders the committed
`docs/example-report.md` from the `commerce-good` golden fixture (never a
live scan, so the published example can't drift from the engine or leak a
real third party's score) — regenerate it with
`python -m scovant_core.docs --example` after any change to the renderer,
the fixture, or the scoring model.
"""
from __future__ import annotations

import sys
from pathlib import Path

from scovant_core import checks as _checks  # noqa: F401 — importing populates registry.CHECKS
from scovant_core.checks.registry import CHECKS
from scovant_core.models import CATEGORY_TITLES, Category
from scovant_core.scoring import CATEGORY_WEIGHTS, GRADES, MIN_COVERAGE

__all__ = ["HEADER", "render_checks", "render_weights_table", "render_example", "main"]

HEADER = "<!-- generated by python -m scovant_core.docs — do not edit -->"

# `docs/checks.md` lives at the package root's `docs/` directory:
# src/scovant_core/docs.py -> parents[0]=scovant_core parents[1]=src parents[2]=<pkg root>
_DOCS_PATH = Path(__file__).resolve().parents[2] / "docs" / "checks.md"


def _profiles_cell(profiles: frozenset[str] | None) -> str:
    return "all" if profiles is None else ", ".join(sorted(profiles))


def _checks_by_category() -> dict[Category, list]:
    grouped: dict[Category, list] = {cat: [] for cat in Category}
    for c in CHECKS:
        grouped[c.category].append(c)
    for cat_checks in grouped.values():
        cat_checks.sort(key=lambda c: c.id)
    return grouped


def render_checks() -> str:
    grouped = _checks_by_category()
    lines: list[str] = [
        HEADER,
        "",
        "# Scovant Core Checks",
        "",
        (
            "Every check the package can run, grouped by category. Regenerated from "
            "`checks/registry.py` by `python -m scovant_core.docs` — do not hand-edit this file."
        ),
        "",
    ]
    for cat in Category:
        cat_checks = grouped[cat]
        if not cat_checks:
            continue
        lines.append(f"## {CATEGORY_TITLES[cat]}")
        lines.append("")
        lines.append("| ID | Title | Weight | Profiles | Severity on fail | Experimental |")
        lines.append("|---|---|---|---|---|---|")
        for c in cat_checks:
            lines.append(
                f"| {c.id} | {c.title} | {c.weight} | {_profiles_cell(c.profiles)} "
                f"| {c.severity_on_fail.value} | {'yes' if c.experimental else 'no'} |"
            )
        lines.append("")
        for c in cat_checks:
            lines.append(f"### {c.id} — {c.title}")
            lines.append("")
            lines.append(f"**Why it matters:** {c.why_it_matters}")
            lines.append("")
            lines.append(f"**Limitations:** {c.limitations}")
            lines.append("")
            if c.cloud_extension:
                lines.append(f"**Cloud extension:** {c.cloud_extension}")
                lines.append("")
            if c.references:
                lines.append("**References:**")
                lines.append("")
                for ref in c.references:
                    lines.append(f"- <{ref}>")
                lines.append("")
    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines) + "\n"


def _grade_ranges() -> list[tuple[int, int, str]]:
    ordered = sorted(GRADES, key=lambda pair: pair[0], reverse=True)
    ranges: list[tuple[int, int, str]] = []
    upper = 100
    for floor, grade in ordered:
        ranges.append((floor, upper, grade))
        upper = floor - 1
    return ranges


def render_weights_table() -> str:
    lines: list[str] = ["| Category | Weight |", "|---|---:|"]
    for cat in Category:
        lines.append(f"| {CATEGORY_TITLES[cat]} | {CATEGORY_WEIGHTS[cat.value]} |")
    lines.append(f"| **Total** | **{sum(CATEGORY_WEIGHTS.values())}** |")
    lines.append("")
    lines.append(
        f"Minimum evidence coverage: {round(MIN_COVERAGE * 100)}%. Below this coverage, "
        "no score is emitted (`INSUFFICIENT_EVIDENCE`) instead of scoring on whatever few "
        "checks happened to evaluate."
    )
    lines.append("")
    lines.append("| Score | Grade |")
    lines.append("|---|---|")
    for floor, upper, grade in _grade_ranges():
        lines.append(f"| {floor}–{upper} | {grade} |")
    return "\n".join(lines)


def render_example() -> str:
    """The published example report, rendered from the `commerce-good` golden
    fixture — never from a live scan, so it cannot drift from the engine and
    never publishes a real third party's score."""
    import json

    from scovant_core.models import Report
    from scovant_core.report.markdown import render_markdown

    golden = Path(__file__).resolve().parents[2] / "fixtures" / "sites" / "expected" / "commerce-good.json"
    report = Report.model_validate(json.loads(golden.read_text(encoding="utf-8")))
    return (
        "# Example report\n\n"
        "Generated from the `commerce-good` fixture by "
        "`python -m scovant_core.docs --example`. Do not edit by hand.\n\n"
        + render_markdown(report, utm_medium="docs").rstrip("\n") + "\n"
    )


_EXAMPLE_PATH = Path(__file__).resolve().parents[2] / "docs" / "example-report.md"


def main(argv: list[str] | None = None) -> int:
    """`python -m scovant_core.docs [--example]` — rewrites the committed
    `docs/checks.md`, or `docs/example-report.md` with `--example`."""
    args = list(sys.argv[1:] if argv is None else argv)
    unknown = [a for a in args if a != "--example"]
    if unknown:
        print(f"usage: python -m scovant_core.docs [--example] (unknown argument: {unknown[0]})",
              file=sys.stderr)
        return 2
    if not _DOCS_PATH.parent.is_dir():
        print("python -m scovant_core.docs writes the repository's docs/ directory, which is "
              "not present here (installed package?). Run it from a checkout.", file=sys.stderr)
        return 2
    if "--example" in args:
        _EXAMPLE_PATH.write_text(render_example(), encoding="utf-8")
    else:
        _DOCS_PATH.write_text(render_checks(), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
